jsons:
  - "data/processed/asos-season-large-evaporation.json"
  - "data/processed/aws-season-precipitation.json"

args:
  start_date: "2024-01-01"
  end_date: "2024-12-31"

  precipitation: 1
  large_evaporation: 0

  start_capacity: 80

  data: "data/raw/한국농어촌공사_전국 저수지 일별 저수율_20241231.csv"
  name: "오봉"
  loc: "강원특별자치도 강릉시"

model:
  type: "SeasonModel"